### ISSUE TITLE
Branch Merge Issue

### ISSUE THREAD

**Issue by jatinrampal** [jatinrampal/WhiteBears-Capstone#10]
Dashboard and Login(Master) branches throw up an error when a pull request is submitted to merge the two. @KishanDalal and @rosekal need to look into this since you guys were the one who were working with these specific branches.

**Comment by KishanDalal** [comment]
See Slack.

**Comment by rosekal** [comment]
I wish this was brought to my attention earlier.  Oh well.  Fixed now.

**Comment by KishanDalal** [comment]
Wasn't this fixed a while ago? The current solution i cloned from Master few days ago seems to be fine.

**Comment by rosekal** [comment]
I cloned the master branch earlier today to test, the login view couldn't connect to the controller due to routing issues.

**Comment by jatinrampal** [comment]
I'm going to reopen the issue for now.

**Comment by rosekal** [comment]
It's been solved earlier today by your's truly.  Closing again.  See slack please.

**Comment by KishanDalal** [comment]
Isn't this the same bug I mentioned on slack?
