### ISSUE TITLE
Tasks duplicating

### ISSUE THREAD

**Issue by rosekal** [jatinrampal/WhiteBears-Capstone#100]
Everytime I add a task & refresh, it duplicates the task

Project Page
![image](https://user-images.githubusercontent.com/19345260/48975988-3f996b80-f04c-11e8-88d9-950e6e7f52a7.png)

On back-end, there's only one record.  Seems like a front-end problem.  ID 172 and 174 are the taskIds of the aforementioned Task rows

![image](https://user-images.githubusercontent.com/19345260/48976002-930bb980-f04c-11e8-9cde-4b20386458a8.png)

**Comment by KishanDalal** [comment]
This only seem to be apply if you create a Task as a Project Manager and assign it to a Project Manager. Seems to be working fine for normal users.

**Comment by rosekal** [comment]
No this is happening if I assign multiple people.  Right now if I create one task, it displays it 4 times.  Assigned to Jatin

![image](https://user-images.githubusercontent.com/19345260/48981125-98462400-f09f-11e8-8013-f5f38163bf06.png)

**Comment by KishanDalal** [comment]
Figured it out. See if it works for you.

**Comment by rosekal** [comment]
Good now
