### ISSUE TITLE
Scrolling functionality to Tasks table

### ISSUE THREAD

**Issue by jatinrampal** [jatinrampal/WhiteBears-Capstone#12]

**Comment by rosekal** [comment]
Again, please be specific regarding this.  Scrolling works on my end.  Does it not scroll?  Does it overflow?  What is the issue?

**Comment by jatinrampal** [comment]
The issues have been listed on Trello. Just moving them over here. If they have been resolved, close them.

**Comment by rosekal** [comment]
It's redundant to create new issues on GitHub that have already been resolved (apparent, as they are under the "fixed bugs and improvements" list.  If anything transfer the ones that are in "known bugs and improvements".

**Comment by rosekal** [comment]
With that I will close both this issue and the add button issue.
