### ISSUE TITLE
Login Error Message Illegible

### ISSUE THREAD

**Issue by rosekal** [jatinrampal/WhiteBears-Capstone#14]
When the user enters the wrong username/password, the error message blends in with the background.

![image](https://user-images.githubusercontent.com/19345260/46804066-ba722580-cd2f-11e8-9d62-502e13cc2e46.png)

**Comment by jatinrampal** [comment]
Also, would really appreciate if the login page is created to have a similar UI as to the dashboards and the project pages. Nav Bars need to be consistent throughout the web application.

**Comment by rosekal** [comment]
Nav bar isn't necessary on the login page.  Project page on the other hand, I agree, but it's outside the scope of this issue.

**Comment by rosekal** [comment]
Any updates on this?

**Comment by rosekal** [comment]
It's been fixed by placing the textboxes & messages on the white part of the login page
