### ISSUE TITLE
Azure Storage Containers

### ISSUE THREAD

**Issue by jatinrampal** [jatinrampal/WhiteBears-Capstone#17]
Having this here for visibility purposes. Struggling to implement multiple Azure blob containers into the Storage to allow multiple project based storaged details.

**Comment by rosekal** [comment]
Are you getting an error?  Does it only allow one blob container?

**Comment by rosekal** [comment]
Personally I don't think I will be much of help since I don't have experience with Azure data storage.

**Comment by jatinrampal** [comment]
You can add as many containers as you want. They are just limited by the storage. You can't create a container by code. It has to exist already.

**Comment by jatinrampal** [comment]
I self-assigned this. The help-wanted tag is more for when we have the final two sprints.

**Comment by rosekal** [comment]
Data limitation is definitely an issue but it's justified if we can't fix it, we're not paying for more storage just to prove a point and graduate.

**Comment by jatinrampal** [comment]
As discussed during the Capstone meeting today, now implementing corporation wide blob containers.

**Comment by jatinrampal** [comment]
Database with Blobs seems to be causing an issue.

**Comment by rafsig** [comment]
You can get the project storage by adding each individual file size for that project. There is a method I've done on your blobstorage class. you can base on that to do it with we have enough time at the end. it would be good to have both statistics displayed as the pm can decide to remove documents versions to free space

**Comment by rosekal** [comment]
Is this still an issue?
