### ISSUE TITLE
Blob Storage Branch issue

### ISSUE THREAD

**Issue by rosekal** [jatinrampal/WhiteBears-Capstone#22]
There is a pull request issue and it needs to be solved ASAP so Rafael can get into it.

**Comment by rosekal** [comment]
![image](https://user-images.githubusercontent.com/19345260/47268659-7a762400-d521-11e8-9c1f-eb876677c09d.png)
Now there's an error message when cloning the master branch.  Original project runs fine.  Your project doesn't load.

**Comment by rosekal** [comment]
The random folder is still on the master branch.  Not sure if this is solved or not, please keep us updated.

**Comment by jatinrampal** [comment]
Versioning issues have been long resolved.
