### ISSUE TITLE
Tables minimum size

### ISSUE THREAD

**Issue by rafsig** [jatinrampal/WhiteBears-Capstone#26]
@rosekal add size for the tables containers (divs) so the view keeps consistent independently from how many tasks and notes we have on the table

**Comment by rosekal** [comment]
This has already been solved on the master branch

**Comment by rosekal** [comment]
#TasksSection {
    float: left;
    margin-left: 50px;
    margin-top: 20px;
    min-height: 300px;
    **min-width: 550px;**
}
