### ISSUE TITLE
Document Review: Same Version Comparisons

### ISSUE THREAD

**Issue by rosekal** [jatinrampal/WhiteBears-Capstone#28]
Should have the combo box on the right change to another value if user chooses the exact same value as the combo box on the right, or even removing it from the right combo box all together.

All in all, user shouldn't be able to select the same version.

![image](https://user-images.githubusercontent.com/19345260/47826512-c198bc00-dd4e-11e8-86dd-ae55d9de67c7.png)

**Comment by rafsig** [comment]
Won´t change the code
