### ISSUE TITLE
Can Access Any Project Via URL

### ISSUE THREAD

**Issue by rosekal** [jatinrampal/WhiteBears-Capstone#32]
I'm able to access any project by just appending a number in the URL.

![image](https://user-images.githubusercontent.com/19345260/47888080-df325800-de18-11e8-8ad0-eb2eb3c0a13c.png)

I don't have access to it on the database, it should be reflected here.

![image](https://user-images.githubusercontent.com/19345260/47888090-ee190a80-de18-11e8-9b83-b23c0b4dbaf4.png)

**Comment by rosekal** [comment]
I have access to id #1, #2, #4, and #5.  Not #3

**Comment by KishanDalal** [comment]
Completed
