### ISSUE TITLE
Document Download Improvements

### ISSUE THREAD

**Issue by rosekal** [jatinrampal/WhiteBears-Capstone#37]
1. There's no notification when the download commences.  This could mislead the client into thinking that it didn't do anything at all, making them click the download link again and again.

2. Furthermore, it doesn't alert you when it's fully downloaded.  Again can mislead the client in a similar manner as previously mentioned.

3. It doesn't tell the user where the file was downloaded.  I had to search my entire computer because I was unsure of where it downloaded (considering the C:/WhiteBears path beforehand, I was confused)

4. When downloaded, it overwrites the file if it has the same name without confirmation.  This can be very troublesome.

5. It doesn't open the file automatically.  This can be subjective, but there should be an option to do so
As for the upload part, I'm getting a different error message now

**Comment by jatinrampal** [comment]
Closing the issue since downloads take place through Chrome.
