### ISSUE TITLE
Buttons that should be disabled by default in Project Page

### ISSUE THREAD

**Issue by rosekal** [jatinrampal/WhiteBears-Capstone#45]
When accessing the Project Page, delete buttons should be disabled as no row are selected.  On select, enable the button.  On deselecting all rows, disable the button.  On-clicking delete, it refreshes the page for no reason if no rows were selected.

Furthermore, "version compare" button should also be disabled as no rows are selected.  If the user selects an xls file to version compare, they will be mislead that our system supports the version compare of xls files.  It's best to only enable the button when they click on rows that are docx files.

![image](https://user-images.githubusercontent.com/19345260/48198944-8ab33f00-e328-11e8-9371-5723f8610560.png)

**Comment by KishanDalal** [comment]
Different implementation for UI (personally I think it's more user friendly this way).
