### ISSUE TITLE
Document Revision: Showing invalid version number

### ISSUE THREAD

**Issue by rosekal** [jatinrampal/WhiteBears-Capstone#59]
There's no version 1 of Kalen.docx, yet it has version 1 as a selection in the document revision page

![versions_1](https://user-images.githubusercontent.com/19345260/48456485-3e835700-e78d-11e8-97c7-2d2ba096bfaf.JPG)
![versions](https://user-images.githubusercontent.com/19345260/48456486-3e835700-e78d-11e8-8899-417352a48a82.JPG)

**Comment by rafsig** [comment]
Need to implement a remove blob that removes the file from blob storage and DB

**Comment by rafsig** [comment]
The method should have as input: document id and version
If there are no more versions for that document (all deleted) it should remove from the document table and document role table also.

**Comment by rafsig** [comment]
Fixed, new files won't cause problems
