### ISSUE TITLE
Dashboard layout

### ISSUE THREAD

**Issue by rafsig** [jatinrampal/WhiteBears-Capstone#66]
![dashboard](https://user-images.githubusercontent.com/32227253/48662497-c64cb800-ea50-11e8-88a6-3d2e224e7440.png)

This is looking weird, need to take a look on what is happening. It was working and suddenly this happened. Have you seen it and maybe fixed?

**Comment by rosekal** [comment]
Works fine on my 1920x1080 monitor

![image](https://user-images.githubusercontent.com/19345260/48664478-e9856080-ea6c-11e8-99fd-f87653e56b42.png)

**Comment by rosekal** [comment]
Works fine on my 1920x1080 monitor

![image](https://user-images.githubusercontent.com/19345260/48664487-15a0e180-ea6d-11e8-9c27-fe7378971c79.png)

**Comment by rosekal** [comment]
I have changed the width percentage values for task table and progress bars.  Zoomed in to 110%, got this.  Should be working now

![image](https://user-images.githubusercontent.com/19345260/48664627-7cbf9580-ea6f-11e8-8e93-f73ade9e270f.png)

**Comment by rosekal** [comment]
I'll leave it open until I get confirmation

**Comment by rafsig** [comment]
Fix side bar height and position

**Comment by rosekal** [comment]
Fixed the side bar height
