### ISSUE TITLE
Project page: document row picking

### ISSUE THREAD

**Issue by rosekal** [jatinrampal/WhiteBears-Capstone#67]
End user should not have to deselect (clicking on the selected row again) in order to select another row.

![image](https://user-images.githubusercontent.com/19345260/48664562-754bbc80-ea6e-11e8-8634-1c9826764f6f.png)

**Comment by rosekal** [comment]
Not sure who was working on this one so I assigned both Raf and Kishan

**Comment by KishanDalal** [comment]
Not Enough Time for this issue to be finished.
