### ISSUE TITLE
Document Version Comparison: modified by empty

### ISSUE THREAD

**Issue by rosekal** [jatinrampal/WhiteBears-Capstone#68]
Modified by is empty on the left side.  Not sure if this is a DB insertion issue or the View's issue.
![image](https://user-images.githubusercontent.com/19345260/48665552-8ef50000-ea7e-11e8-91f5-0cecb3ecd93c.png)

**Comment by rosekal** [comment]
Not sure if this is a DB insertion issue or the View's issue.  Assigning both Raf and Jatin

**Comment by rafsig** [comment]
fixed
