### ISSUE TITLE
Unable to Download Files

### ISSUE THREAD

**Issue by jatinrampal** [jatinrampal/WhiteBears-Capstone#69]
The current published version makes it unable to download files.

**Comment by rosekal** [comment]
Personally I'm getting this error message.

![image](https://user-images.githubusercontent.com/19345260/48665718-7803dd00-ea81-11e8-8cbb-e80ff14c7eba.png)

**Comment by rosekal** [comment]
I'm not sure if it's Jatin's or Raf's doing here

**Comment by rosekal** [comment]
If there's no document on the server, there shouldn't be an entry on the Blob storage page for that document.

Before clicking the Uri link
![image](https://user-images.githubusercontent.com/19345260/48724328-efa74880-ebf6-11e8-9eeb-9d294b738d5f.png)

After clicking on the Uri link
![image](https://user-images.githubusercontent.com/19345260/48724428-2f6e3000-ebf7-11e8-9431-1c60befa3dbd.png)

**Comment by jatinrampal** [comment]
Downloads working through Chrome now.
