### ISSUE TITLE
Dashboard personal note minimum width and height

### ISSUE THREAD

**Issue by rafsig** [jatinrampal/WhiteBears-Capstone#74]
![image](https://user-images.githubusercontent.com/32227253/48734559-c0530480-ec13-11e8-9086-3ab5f22598df.png)

**Comment by rafsig** [comment]
Laptop view

![image](https://user-images.githubusercontent.com/32227253/48734696-335c7b00-ec14-11e8-8d13-680735b03732.png)

**Comment by rosekal** [comment]
Was fixed already, Raf confirmed
