### ISSUE TITLE
Not all document information showing on DocumentReview page

### ISSUE THREAD

**Issue by rosekal** [jatinrampal/WhiteBears-Capstone#76]
I uploaded this document (that will become version 3)
![image](https://user-images.githubusercontent.com/19345260/48750725-a4b91f80-ec4e-11e8-8d11-d26b063e42ec.png)

This is what I get on the documentreview page  
![image](https://user-images.githubusercontent.com/19345260/48750750-bbf80d00-ec4e-11e8-944b-284694041a7e.png)

Document used: KR_TEST

**Comment by rafsig** [comment]
Bug due to content added to the document by the free version of the API, I created a walk around for this problems and now it is fixed.
