### ISSUE TITLE
Document Review: Comparing Versions Issues 

### ISSUE THREAD

**Issue by rosekal** [jatinrampal/WhiteBears-Capstone#77]
Right now it only compares from what has been changed from the left and to the right.  But what if I choose a higher version (v2) on the left, and an older version (v1) on the right?  Unexpected results happen, regardless if the algorithm works, since I haven't changed the older version at all.

It should detect what number is higher and compare it from the lower version to the higher version, or strictly only allow the lower version on the left, and a higher version on the right.

![image](https://user-images.githubusercontent.com/19345260/48751367-fd3dec00-ec51-11e8-9f53-594b1649a799.png)

**Comment by rafsig** [comment]
fixed
