### ISSUE TITLE
Document Review Index Page Layout

### ISSUE THREAD

**Issue by rosekal** [jatinrampal/WhiteBears-Capstone#80]
The current styling of the Document Review index page doesn't look up to date. Please follow the header styling shown in Dashboard, Project Page, Team Management, Admin Home, etc.

![image](https://user-images.githubusercontent.com/19345260/48752509-a9ce9c80-ec57-11e8-810a-5fa5ef084d87.png)

**Comment by rafsig** [comment]
Fixed
