### ISSUE TITLE
Not Able To Upload

### ISSUE THREAD

**Issue by rosekal** [jatinrampal/WhiteBears-Capstone#84]
Can't upload anything via Project Page.

This is what the page looks like right before submitting.
![image](https://user-images.githubusercontent.com/19345260/48882924-28a80e80-edeb-11e8-8b15-62656b7ef6f8.png)

After submitting, sometimes it takes me to the dashboard, but most times it gives me this message.
![image](https://user-images.githubusercontent.com/19345260/48882901-0d3d0380-edeb-11e8-8d9d-393714b983c5.png)

If it takes me to the dashboard, nothing was uploaded anyway.

**Comment by jatinrampal** [comment]
From what I see, the reason you got an error was because the ProjectID and the role weren't passed as parameters.

**Comment by rosekal** [comment]
Ok but it was passed as parameters on the UploadBlob page itself, check the second first screenshot in the URL

**Comment by rosekal** [comment]
I've also done it through the project page itself.  I don't know if it's your issue or Kishan's.

**Comment by jatinrampal** [comment]
This has now been resolved as part of the latest commit.
