### ISSUE TITLE
Remaining Storage Info

### ISSUE THREAD

**Issue by jatinrampal** [jatinrampal/WhiteBears-Capstone#86]
<img width="405" alt="screen shot 2018-11-22 at 1 58 36 pm" src="https://user-images.githubusercontent.com/20634201/48919075-c0931000-ee5e-11e8-80d4-9d41118d5865.png">

Storage info precise to two decimal points.

**Comment by rosekal** [comment]
Bad labels used.  Not a bug, everything is working.  Not high priority, due to it still working regardless.

Fixed nonetheless, changed a line of code.
