### ISSUE TITLE
Document Download Error 

### ISSUE THREAD

**Issue by KishanDalal** [jatinrampal/WhiteBears-Capstone#93]
![image](https://user-images.githubusercontent.com/23020740/48973874-b7996e80-f017-11e8-86b0-e2f23c6469b8.png)

When selecting and trying to download a Document from the Project Page it's erroring here.

**Comment by rafsig** [comment]
This happens when DB doesn´t match with Blob storage, Jatin I suppose this is fixed right?

**Comment by jatinrampal** [comment]
I need more context as to why does this issue exist?

**Comment by jatinrampal** [comment]
<img width="1414" alt="screen shot 2018-11-24 at 7 44 24 pm" src="https://user-images.githubusercontent.com/20634201/48974259-8625a080-f021-11e8-96b3-0005d9007b0b.png">
Still seeing the network error when attempting to download a file.

**Comment by jatinrampal** [comment]
Also, looked into the DownloadToStream issue and yes this does occur when the database isn't consistent with the storage. This shouldn't persist once the database is updated with values again from scratch. But still have no clue as to why the network error is showing up and this is definitely high priority.

**Comment by rafsig** [comment]
![image](https://user-images.githubusercontent.com/32227253/48974328-2e883480-f023-11e8-8351-9001ec28f150.png)
Don´t see any problem with this

**Comment by KishanDalal** [comment]
That's not current Master. Whatever happened between that and now something must have changed.

**Comment by rafsig** [comment]
@KishanDalal you didn´t check the conflicts while merging your code, and that changed my code to what was before, now it is fixed, please, if pushing anything new check for conflicts on project page index

**Comment by rafsig** [comment]
@KishanDalal fixed problem, please check for conflicts and resolve then when committing your changes

**Comment by KishanDalal** [comment]
@rafsig  Cool, thought you were done with project page. Let know if you were on Project Page again, ill look at it more closely. My bad I was merging massive amounts of code and I was under the impression you were done with the page.
