### ISSUE TITLE
Can't Add Users to Task

### ISSUE THREAD

**Issue by rosekal** [jatinrampal/WhiteBears-Capstone#99]
Can't add current users that are added to the project via Team Management to a task

I've added "Raf" to the project

![image](https://user-images.githubusercontent.com/19345260/48975970-c863d780-f04b-11e8-88c9-370727dab3dd.png)

Here's the only option
![image](https://user-images.githubusercontent.com/19345260/48975967-b8e48e80-f04b-11e8-8e92-48ba2ef19597.png)

Raf is added to that project on back-end just fine, seems to be a Project Page front-end problem.  58 is the project Id of WhiteBears

![image](https://user-images.githubusercontent.com/19345260/48975976-03fea180-f04c-11e8-968d-35dbd72a41ba.png)

**Comment by KishanDalal** [comment]
Raf, is an Admin.

**Comment by rosekal** [comment]
AHHHHHHHHHHHHHHHHHHHHH

**Comment by rosekal** [comment]
Fair point.  You can close
